### ISSUE TITLE
How to get authors of a book?

### ISSUE THREAD

**Issue by ghost** [netvlies/bol-openapi-php-sdk#1]
I made a successful call to Bol.com and received some products (books in my case). How can i get the author of a product? Because the function $product->getAuthors() is not available.

**Comment by ricbra** [comment]
The model should contain a <code>getAuthor</code> method: https://github.com/netvlies/bol-openapi-php-sdk/blob/master/src/BolOpenApi/Model/Book.php#L84

Can you give some information about the <code>$product</code> var?

**Comment by ghost** [comment]
Thanks for the reply.

This is my code to do a ISBN search:

```
    $httpBrowser     = new \Buzz\Browser();
    $accessKey       = 'xxx';
    $secretAccessKey = 'xxx';
    $isbn = '9780470753958';
    $apiClient       = new \BolOpenApi\Client($accessKey, $secretAccessKey, $httpBrowser);
    $options         = array(
        'nrProducts'     => 1,
        'sortingMethod'  => \BolOpenApi\Enum\SortingMethod::PRICE,
        'productType'    => \BolOpenApi\Enum\ProductType::BOOK,
        'offerStateType' => \BolOpenApi\Enum\OfferStateType::IS_NEW,
    );
    $searchResult = $apiClient->searchResults($isbn, $options);

    $products = $searchResult->getProducts();   
    return $products;
```

It returns this object

![image](https://f.cloud.github.com/assets/4396386/895422/0f98a890-facc-11e2-9581-db0e7d3e382b.png)

I can see the authors entity, i dont know how to extract them.

**Comment by ricbra** [comment]
As far as I can see your <code>$products</code> variable is an array containing one entry. Thus to extract the author(s):

``` php
foreach ($products as $product) {
    // $product is in fact BolOpenApi\Model\Book
    $authors = $product->getAuthors();
    foreach ($authors as $author) {
        // Do wicked stuff with author
    }
}
```

**Comment by ghost** [comment]
Wow, that easy huh. I got confused because the ->getAuthor(); and later on the ->getName(); functions werent available in my IDE's autocompletion, so i assumed it wasnt there.
